---
- hosts: group_A, group_B
  become: yes
  gather_facts: no
  vars_files:
    - ./host_vars/db_and_web_server1.yml
  tasks:
    - name: Install dependencies
      yum: name={{ item }} state=installed
      with_items:
        - MySQL-python
        - python-pip

    - include: tasks/deploy_db.yml
      when: "'group_A' in group_names"
    - include: tasks/deploy_web.yml
      when: "'group_A' in  group_names"
    - include: tasks/install_deploy_jenkins.yml
      when: "'group_B' in group_names"
